/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/config": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.config.id"];
          created_at?: parameters["rowFilter.config.created_at"];
          SendErrorsShowMessage?: parameters["rowFilter.config.SendErrorsShowMessage"];
          Name?: parameters["rowFilter.config.Name"];
          Port?: parameters["rowFilter.config.Port"];
          ResourceFolder?: parameters["rowFilter.config.ResourceFolder"];
          AuthKey?: parameters["rowFilter.config.AuthKey"];
          Private?: parameters["rowFilter.config.Private"];
          MaxPlayers?: parameters["rowFilter.config.MaxPlayers"];
          Debug?: parameters["rowFilter.config.Debug"];
          Description?: parameters["rowFilter.config.Description"];
          MaxCars?: parameters["rowFilter.config.MaxCars"];
          Map?: parameters["rowFilter.config.Map"];
          SendErrors?: parameters["rowFilter.config.SendErrors"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["config"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** config */
          config?: definitions["config"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.config.id"];
          created_at?: parameters["rowFilter.config.created_at"];
          SendErrorsShowMessage?: parameters["rowFilter.config.SendErrorsShowMessage"];
          Name?: parameters["rowFilter.config.Name"];
          Port?: parameters["rowFilter.config.Port"];
          ResourceFolder?: parameters["rowFilter.config.ResourceFolder"];
          AuthKey?: parameters["rowFilter.config.AuthKey"];
          Private?: parameters["rowFilter.config.Private"];
          MaxPlayers?: parameters["rowFilter.config.MaxPlayers"];
          Debug?: parameters["rowFilter.config.Debug"];
          Description?: parameters["rowFilter.config.Description"];
          MaxCars?: parameters["rowFilter.config.MaxCars"];
          Map?: parameters["rowFilter.config.Map"];
          SendErrors?: parameters["rowFilter.config.SendErrors"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.config.id"];
          created_at?: parameters["rowFilter.config.created_at"];
          SendErrorsShowMessage?: parameters["rowFilter.config.SendErrorsShowMessage"];
          Name?: parameters["rowFilter.config.Name"];
          Port?: parameters["rowFilter.config.Port"];
          ResourceFolder?: parameters["rowFilter.config.ResourceFolder"];
          AuthKey?: parameters["rowFilter.config.AuthKey"];
          Private?: parameters["rowFilter.config.Private"];
          MaxPlayers?: parameters["rowFilter.config.MaxPlayers"];
          Debug?: parameters["rowFilter.config.Debug"];
          Description?: parameters["rowFilter.config.Description"];
          MaxCars?: parameters["rowFilter.config.MaxCars"];
          Map?: parameters["rowFilter.config.Map"];
          SendErrors?: parameters["rowFilter.config.SendErrors"];
        };
        body: {
          /** config */
          config?: definitions["config"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/logfiles": {
    get: {
      parameters: {
        query: {
          filename?: parameters["rowFilter.logfiles.filename"];
          imported_at?: parameters["rowFilter.logfiles.imported_at"];
          created_at?: parameters["rowFilter.logfiles.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["logfiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** logfiles */
          logfiles?: definitions["logfiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          filename?: parameters["rowFilter.logfiles.filename"];
          imported_at?: parameters["rowFilter.logfiles.imported_at"];
          created_at?: parameters["rowFilter.logfiles.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          filename?: parameters["rowFilter.logfiles.filename"];
          imported_at?: parameters["rowFilter.logfiles.imported_at"];
          created_at?: parameters["rowFilter.logfiles.created_at"];
        };
        body: {
          /** logfiles */
          logfiles?: definitions["logfiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/user": {
    get: {
      parameters: {
        query: {
          username?: parameters["rowFilter.user.username"];
          last_connexion?: parameters["rowFilter.user.last_connexion"];
          nb_connexions?: parameters["rowFilter.user.nb_connexions"];
          guest?: parameters["rowFilter.user.guest"];
          created_at?: parameters["rowFilter.user.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["user"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** user */
          user?: definitions["user"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          username?: parameters["rowFilter.user.username"];
          last_connexion?: parameters["rowFilter.user.last_connexion"];
          nb_connexions?: parameters["rowFilter.user.nb_connexions"];
          guest?: parameters["rowFilter.user.guest"];
          created_at?: parameters["rowFilter.user.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          username?: parameters["rowFilter.user.username"];
          last_connexion?: parameters["rowFilter.user.last_connexion"];
          nb_connexions?: parameters["rowFilter.user.nb_connexions"];
          guest?: parameters["rowFilter.user.guest"];
          created_at?: parameters["rowFilter.user.created_at"];
        };
        body: {
          /** user */
          user?: definitions["user"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** @description Config */
  config: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: boolean */
    SendErrorsShowMessage?: boolean;
    /** Format: text */
    Name?: string;
    /** Format: smallint */
    Port?: number;
    /** Format: text */
    ResourceFolder?: string;
    /** Format: text */
    AuthKey?: string;
    /** Format: boolean */
    Private?: boolean;
    /** Format: smallint */
    MaxPlayers?: number;
    /** Format: boolean */
    Debug?: boolean;
    /** Format: text */
    Description?: string;
    /** Format: smallint */
    MaxCars?: number;
    /** Format: text */
    Map?: string;
    /** Format: boolean */
    SendErrors?: boolean;
  };
  /** @description log files imported */
  logfiles: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    filename: string;
    /** Format: timestamp without time zone */
    imported_at: Date;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
  };
  /** @description Users */
  user: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    username: string;
    /** Format: timestamp without time zone */
    last_connexion: string;
    /** Format: smallint */
    nb_connexions?: number;
    /** Format: boolean */
    guest: boolean;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description config */
  "body.config": definitions["config"];
  /** Format: bigint */
  "rowFilter.config.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.config.created_at": string;
  /** Format: boolean */
  "rowFilter.config.SendErrorsShowMessage": string;
  /** Format: text */
  "rowFilter.config.Name": string;
  /** Format: smallint */
  "rowFilter.config.Port": string;
  /** Format: text */
  "rowFilter.config.ResourceFolder": string;
  /** Format: text */
  "rowFilter.config.AuthKey": string;
  /** Format: boolean */
  "rowFilter.config.Private": string;
  /** Format: smallint */
  "rowFilter.config.MaxPlayers": string;
  /** Format: boolean */
  "rowFilter.config.Debug": string;
  /** Format: text */
  "rowFilter.config.Description": string;
  /** Format: smallint */
  "rowFilter.config.MaxCars": string;
  /** Format: text */
  "rowFilter.config.Map": string;
  /** Format: boolean */
  "rowFilter.config.SendErrors": string;
  /** @description logfiles */
  "body.logfiles": definitions["logfiles"];
  /** Format: text */
  "rowFilter.logfiles.filename": string;
  /** Format: timestamp without time zone */
  "rowFilter.logfiles.imported_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.logfiles.created_at": string;
  /** @description user */
  "body.user": definitions["user"];
  /** Format: text */
  "rowFilter.user.username": string;
  /** Format: timestamp without time zone */
  "rowFilter.user.last_connexion": string;
  /** Format: smallint */
  "rowFilter.user.nb_connexions": string;
  /** Format: boolean */
  "rowFilter.user.guest": string;
  /** Format: timestamp with time zone */
  "rowFilter.user.created_at": string;
}

export interface operations {}

export interface external {}
